version: "3"
services:

  db:
    image: mysql:5.7
    container_name: db_immo
    restart: always
    volumes:
      - db:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    networks:
      - dev

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin_immo
    restart: always
    depends_on:
      - db
    ports:
      - 8080:80
    environment:
      PMA_HOST: db
      MAX_EXECUTION_TIME: 3600
      UPLOAD_LIMIT: 1024M
    networks:
      - dev

  back:
    build: docker
    container_name: back_immo
    ports:
      - "80:80"
    volumes:
      - ./docker/vhost.conf:/etc/apache2/sites-enabled/vhosts.conf
      - ./:/var/www
      - ./docker/php.ini:/usr/local/etc/php/php.ini
    restart: always
    networks:
      - dev

networks:
  dev:

volumes:
  db: